version: '3'
services:
  postgres:
    image: postgres:12.3
    environment:
      POSTGRES_USER: "library"
      POSTGRES_PASSWORD: "library"
      POSTGRES_DB: "library"
    ports:
      - 5432:5432
